/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author corre
 */
public class Tecnicos extends javax.swing.JFrame {

    /**
     * Creates new form Tecnicos
     */
    public Tecnicos() {
        initComponents();
         this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        bynInicio = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnUbicacion = new javax.swing.JButton();
        btnSer = new javax.swing.JButton();
        btnFecha = new javax.swing.JButton();
        btnConsir = new javax.swing.JButton();
        btnsecion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/hh.jpg"))); // NOI18N

        bynInicio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bynInicio.setText("Inicio");
        bynInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bynInicioActionPerformed(evt);
            }
        });

        btnCliente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCliente.setText("Cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnUbicacion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnUbicacion.setText("Ubicación");
        btnUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbicacionActionPerformed(evt);
            }
        });

        btnSer.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSer.setText("Datos servicio");
        btnSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerActionPerformed(evt);
            }
        });

        btnFecha.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnFecha.setText("Fecha Visita");
        btnFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechaActionPerformed(evt);
            }
        });

        btnConsir.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnConsir.setText("Comfirmación");
        btnConsir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsirActionPerformed(evt);
            }
        });

        btnsecion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnsecion.setText("Inicio de seción");
        btnsecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsecionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bynInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUbicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsir)
                .addGap(38, 38, 38)
                .addComponent(btnsecion)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bynInicio)
                    .addComponent(btnCliente)
                    .addComponent(btnUbicacion)
                    .addComponent(btnSer)
                    .addComponent(btnFecha)
                    .addComponent(btnConsir)
                    .addComponent(btnsecion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bynInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bynInicioActionPerformed
        this.setVisible(false);
        Inicio n1=new Inicio();
        n1.setVisible(true);
    }//GEN-LAST:event_bynInicioActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
       this.setVisible(false);
        MenuInicio n1=new MenuInicio();
        n1.setVisible(true);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbicacionActionPerformed
        this.setVisible(false);
        Ubicacion n1=new Ubicacion();
        n1.setVisible(true);
    }//GEN-LAST:event_btnUbicacionActionPerformed

    private void btnSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerActionPerformed
        this.setVisible(false);
        DatosServicio n1=new DatosServicio();
        n1.setVisible(true);
    }//GEN-LAST:event_btnSerActionPerformed

    private void btnFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechaActionPerformed
        this.setVisible(false);
        Visita n1=new Visita();
        n1.setVisible(true);
    }//GEN-LAST:event_btnFechaActionPerformed

    private void btnConsirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsirActionPerformed
        this.setVisible(false);
        Confirmacion n1=new Confirmacion();
        n1.setVisible(true);
    }//GEN-LAST:event_btnConsirActionPerformed

    private void btnsecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsecionActionPerformed
        this.setVisible(false);
        Secion n1=new Secion();
        n1.setVisible(true);
    }//GEN-LAST:event_btnsecionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tecnicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tecnicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tecnicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tecnicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tecnicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnConsir;
    private javax.swing.JButton btnFecha;
    private javax.swing.JButton btnSer;
    private javax.swing.JButton btnUbicacion;
    private javax.swing.JButton btnsecion;
    private javax.swing.JButton bynInicio;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
